disabled_rules:
  # trailing comma is forced by swiftformat
  - trailing_comma

line_length:
  warning: 120
  ignores_urls: true

type_name:
  min_length: 3
  max_length: 50  

opening_brace:
  # this is controlled by `swiftformat` and we can not change config of formatter
  ignore_multiline_statement_conditions: true

excluded:
  - Pods