name: "Build iOS"
description: "Builds the iOS app"
inputs:
  cache-key-prefix:
    description: "Prefix for cache key"
    required: false
    default: "gradle"
  build-command:
    description: "Android build job"
    required: false
    default: "yarn build:android"

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "microsoft"
        java-version: "17"

    - name: Restore Gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-

    - name: Build Android apk
      run: ${{ inputs.build-command }}
      shell: bash
