name: Build Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-library:
      runs-on: ubuntu-latest
      defaults:
        run: 
          working-directory: packages/react-native-advanced-input-mask
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup
          uses: ./.github/actions/setup

        - name: Build package
          run: yarn prepare