name: Build Library

on:
  workflow_call:

jobs:
  build-library:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup
          uses: ./.github/actions/setup

        - name: Build package
          run: yarn prepare