name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/tests.yml

  build-library:
    uses: ./.github/workflows/build-library.yml

  build-android:
    uses: ./.github/workflows/build-android.yml

  build-ios:
    uses: ./.github/workflows/build-ios.yml
