name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build-library:
    uses: ./.github/workflows/build_library.yml

  build-android:
    uses: ./.github/workflows/build_android.yml

  build-ios:
    uses: ./.github/workflows/build_ios.yml
