name: unit-tests

on: workflow_call

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup
          uses: ./.github/actions/setup

        - name: Run unit tests
          run: yarn test --maxWorkers=2 --coverage