name: unit-tests

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/tests.yml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage
